dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: fcloud-provider
  application:    qos-enable: true
    qos-accept-foreign-ip: false 
    qos-port: 22220
    
spring:
  application:
    # Dubbo 应用名称
    name: '@pom.artifactId@'
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
        
server:
  port: 8786
  
  
app:
  # 应用ID(在Apollo服务端新增项目添加的应用ID)
  id: turbo-apollo

apollo:
  # apollo-config-service地址
  meta: http://10.0.0.215:8080