spring:
  application:
    name: api-gateway
server:
  port: 2006
zuul:
  prefix: /myapi
  add-host-header: true
  retryable: false
  routes:
    feign-consumer-hello:
      path: /feign-consumer/hello/**
      serviceId: feign-consumer-hello
    feign-consumer:
      path: /feign-consumer/**
      serviceId: feign-consumer
    ignored-patterns: /**/hello/**
    local:
      path: /local/**
      url: forward:/local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/