eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:10001/eureka/
    instance:
        prefer-ip-address: true
server:
    port: 8888
spring:
    application:
      name: '@pom.artifactId@'
    sleuth:
      sampler:
        probability: 1.0 #(配置这个就可以，1.0表示100%追踪//0.7表示70%追踪)
    zipkin:
      base-url: http://localhost:9441
    cloud:
      sentinel:
        transport:
          dashboard: localhost:8080
        
dubbo:
  provider:
    filter: tracing
  consumer:
    check: false
    filter: tracing
  registry:
    #   The Spring Cloud Dubbo's registry extension
    ##  the default value of dubbo-provider-services is "*", that means to subscribe all providers,
    ##  thus it's optimized if subscriber specifies the required providers.
    address: spring-cloud://localhost
#   The traditional Dubbo's registry also is supported
#   address: zookeeper://127.0.0.1:2181
