# 服务名称
spring:
  application:
    name: '@pom.artifactId@'
# 服务端口号
server:
  port: 10000

#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    # 是否从其他的服务中心同步服务列表（单节点无需配置启用）
    fetch-registry: false
    # 是否将自己作为服务注册到其他Eureka服务注册中心（单节点无需配置启用）
    register-with-eureka: false
